spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/dbpj
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 926626017138-f7c308gtnhcpnbundhdufeeroo1dp44q.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope:
              - email
              - profile
          kakao:
            client-id: fbdf7d2bf59f9a9713e2e9325a495023
            client-secret: fNF0qnl8nsi6j6l0ZnQWdjlGKYUDH3Br
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: nX6jP4IgsXNpJRqbg0Q5
            client-secret: 1vNwHm8Yri
            scope:
              - name
              - email
            #- profile_image
            client-name: Naver
            authorization-grant-type: authorization_code                  # oauth2의 동작 방식은 여러가지가 있는데, 코드를 응답받는 방식으로 진행한다는 의미
            redirect-uri: http://localhost:8080/oauth2/callback/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: error/messages

#echo 'wejfnwkandskjvnwejknfkjvnwekgwnkfnewfjkwnjkwnqkjnkjefwqjknwk'|base64
jwt:
  secret_key: d2VqZm53a2FuZHNranZud2Vqa25ma2p2bndla2d3bmtmbmV3Zmprd25qa3ducWtqbmtqZWZ3cWprbndrCg==
  token-validity-in-seconds: 60 # 24시간
  refresh-token-validity-in-seconds: 604800
#  86400
upload:
  post:
    image:
      location: /Users/kdo6301/Desktop/sharing_platform_server/post/
  member:
    image:
      location: /Users/kdo6301/Desktop/sharing_platform_server/member/



