spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dbpj
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fbdf7d2bf59f9a9713e2e9325a495023
            client-secret: fNF0qnl8nsi6j6l0ZnQWdjlGKYUDH3Br
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#echo 'wejfnwkandskjvnwejknfkjvnwekgwnkfnewfjkwnjkwnqkjnkjefwqjknwk'|base64
jwt:
  secret_key: d2VqZm53a2FuZHNranZud2Vqa25ma2p2bndla2d3bmtmbmV3Zmprd25qa3ducWtqbmtqZWZ3cWprbndrCg==
  token-validity-in-seconds: 86400 # 24시간

upload:
  image:
    location: /Users/kdo6301/Desktop/sharing_platform_server/



